name: introduce me
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: get my name from secrets
        run: |
          echo  Hello, my name is ${{secrets.name}}.
      
      - name: rewrite settings.xml...
        run: |
          # cat ./.github/workflows/settings.xml | sed 's/LETS_GO_AND_FUCK_IT_UP/${{secrets.name}}/g' >> ~/settings.xml
          # echo the new settings.xml below
          # cat ~/settings.xml
          
          echo ================fuck=============
          mkdir -p ~/.m2
          cp ./.github/workflows/settings.xml ~/.m2/settings.xml
          cat ~/.m2/settings.xml
          echo ==============replace the bart username of settings.xml===============
          cat ~/.m2/settings.xml | sed 's/SECRETS_BART_USERNAME/${{ secrets.name }}/g' >> ~/.m2/settings.xml
          echo replace the bart api key of settings.xml
          cat ~/.m2/settings.xml | sed 's/SECRETS_BART_APIKEY/${{ secrets.name }}/g' >> ~/.m2/settings.xml
          cat ~/.m2/settings.xml

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ~/settings.xml

      - name: the end
        run: |
          echo ${{ secrets.name }}----${{ secrets.name1 }}, the end.
